"""empty message

Revision ID: 70ff5fb4923e
Revises: ab4d80c20047
Create Date: 2023-06-09 13:28:39.531076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70ff5fb4923e"
down_revision = "ab4d80c20047"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_nagabus_majsoul_order", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "model_type",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=False,
        )

    with op.batch_alter_table("nonebot_plugin_nagabus_order", schema=None) as batch_op:
        batch_op.alter_column(
            "model_type",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_nagabus_order", schema=None) as batch_op:
        batch_op.alter_column(
            "model_type",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    with op.batch_alter_table(
        "nonebot_plugin_nagabus_majsoul_order", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "model_type",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
