"""empty message

Revision ID: ab4d80c20047
Revises: 24aec3c56623
Create Date: 2023-05-27 15:17:07.619161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4d80c20047'
down_revision = '24aec3c56623'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_nagabus_majsoul_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nonebot_plugin_nagabus_majsoul_order_paipu_uuid'), ['paipu_uuid'], unique=False)

    with op.batch_alter_table('nonebot_plugin_nagabus_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nonebot_plugin_nagabus_order_create_time'), ['create_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_nagabus_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nonebot_plugin_nagabus_order_create_time'))

    with op.batch_alter_table('nonebot_plugin_nagabus_majsoul_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nonebot_plugin_nagabus_majsoul_order_paipu_uuid'))

    # ### end Alembic commands ###
